### ISSUE TITLE
Unable to create config file

### ISSUE THREAD

**Issue by kkarpe-dm** [SamuelMwangiW/oneplace-sms#1]
"Unable to create config file" when installing.

**Comment by SamuelMwangiW** [comment]
Hi @KaylanDigital. Seems good to me. 

Here is the setup I used to recreate:

`docker-compose.yaml`
```YAML
version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/var/www/html"
    ports:
      - "80:80"
    networks:
      - oneplacesms
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/html"
    networks:
      - oneplacesms
  mysql:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'oneplace'
      MYSQL_USER: 'oneplace'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - oneplacesms
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-ppassword" ]
networks:
  oneplacesms:
```

`Dockerfile`
```Dockerfile
FROM php:8.0-fpm-alpine

RUN docker-php-ext-install mysqli pdo pdo_mysql

```

`nginx.conf`
```Nginx
server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
            return 404;
        }

        fastcgi_param HTTP_PROXY "";

        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

}
```

Kindly check your permissions
